version: "3.3"

services:
  #backend
  build: ./api
  environment:
    - DATABASE_URL=postgresql://postgres:postgres@postgres/postgres
    - IRERE_GITHUB_ID=benawad
    - GITHUB_CLIENT_ID=5d5xxxxxxab70
    - GITHUB_CLIENT_SECRET=48xxxxxxxxxxxxd1cd5
    - TWITTER_SECRET_KEY=testtwittersecret
    - TWITER_BEARER_TOKEN=testtwitterbearer
    - TWITTER_API_KEY=testtwitterkey
    - ACCESS_TOKEN_SECRET=8f51exxxxxx7211dd
    - SENTRY_DSN=SIJHFIUSDHIF
    - SECRET_KEY_BASE=TESTING
    - REFRESH_TOKEN_SECRET=dbb85xxxxxx9ebde
    - WEB_URL=http://localhost:3000
    - API_URL=http://localhost:4001
    - PORT=4001
  ports:
    - 4001:4001
  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRE_DB=postgres
  adminer:
