name: "Quibi Web app CI"

on:
  push:
    branches:
      - prod
    path:
      - "web/**"

jobs:
  test:
    name: "test-web-build"
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - run: cd web && yarn dev
      - run: cd web && yarn lint
      - run: cd web && yarn build
        id: build
